Networkteam:
  Import:
    FlowAdaptor:
      importLogger:
        backend: [TYPO3\Flow\Log\Backend\FileBackend, TYPO3\Flow\Log\Backend\AnsiConsoleBackend]
        backendOptions:
          -
            logFileURL: '%FLOW_PATH_DATA%Logs/Networkteam_Import_FlowAdaptor.log'
            createParentDirectories: TRUE
            severityThreshold: '%LOG_INFO%'
            maximumLogFileSize: 10485760
            logFilesToKeep: 1
            logMessageOrigin: FALSE
          -
            severityThreshold: '%LOG_WARN%'
            logMessageOrigin: FALSE