Networkteam:
  Import:
    FlowAdaptor:
      importLogger:
        backend: [Neos\Flow\Log\Backend\AnsiConsoleBackend]
        backendOptions:
          -
            severityThreshold: '%LOG_DEBUG%'
            logMessageOrigin: FALSE